import {
  IconAnchor,
  IconBolt,
  IconBookmark,
  IconBriefcase,
  IconBuilding,
  IconChartBar,
  IconCloud,
  IconCode,
  IconCrown,
  IconDatabase,
  IconDeviceDesktop,
  IconDiamond,
  IconEggs,
  IconFlag,
  IconFlame,
  IconFolder,
  IconFolders,
  IconHeart,
  IconHome,
  IconLock,
  IconPackage,
  IconPalette,
  IconRocket,
  IconServer,
  IconSettings,
  IconShield,
  IconStar,
  IconTarget,
  IconTool,
  IconTrendingUp,
  IconWorld,
} from '@tabler/icons-react'
import type { ComponentType } from 'react'

// Map of icon names to components
export const WORKSPACE_ICONS: Record<string, ComponentType<{ className?: string }>> = {
  eggs: IconEggs,
  folder: IconFolder,
  home: IconHome,
  briefcase: IconBriefcase,
  tool: IconTool,
  chart: IconChartBar,
  target: IconTarget,
  rocket: IconRocket,
  bolt: IconBolt,
  flame: IconFlame,
  diamond: IconDiamond,
  star: IconStar,
  palette: IconPalette,
  package: IconPackage,
  folders: IconFolders,
  desktop: IconDeviceDesktop,
  server: IconServer,
  lock: IconLock,
  world: IconWorld,
  trending: IconTrendingUp,
  settings: IconSettings,
  building: IconBuilding,
  database: IconDatabase,
  code: IconCode,
  cloud: IconCloud,
  heart: IconHeart,
  bookmark: IconBookmark,
  flag: IconFlag,
  crown: IconCrown,
  shield: IconShield,
  anchor: IconAnchor,
}

export const DEFAULT_WORKSPACE_ICON = 'eggs'
